# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the cc_library rs_bindings_from_cc_type_alias_sys.

[package]
name = "rs_bindings_from_cc_type_alias_sys"
edition.workspace = true
license-file.workspace = true
repository.workspace = true
categories.workspace = true

build = "build.rs"

[lib]
path = "lib.rs"

[dependencies]
type_lifetimes_sys = { path = "../../../../cargo/lifetime_annotations/type_lifetimes_sys"}
ast_util_sys = { path = "../../../../cargo/rs_bindings_from_cc/ast_util_sys"}
cc_ir_sys = { path = "../../../../cargo/rs_bindings_from_cc/cc_ir_sys"}


[build-dependencies]
crubit_build = { path =  "../../../../cargo/build"}
