# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the cc_libary function_sys.

[package]
name = "function_sys"
edition = "2021"

build = "build.rs"

[lib]
path = "lib.rs"

[dependencies]
annotation_reader_sys = { path = "../../../../cargo/common/annotation_reader_sys" }
lifetime_annotations_sys = { path = "../../../../cargo/lifetime_annotations/lifetime_annotations_sys" }
lifetime_sys = { path = "../../../../cargo/lifetime_annotations/lifetime_sys" }
lifetime_symbol_table_sys = { path = "../../../../cargo/lifetime_annotations/lifetime_symbol_table_sys" }
type_lifetimes_sys = { path = "../../../../cargo/lifetime_annotations/type_lifetimes_sys" }
ast_util_sys = { path = "../../../../cargo/rs_bindings_from_cc/ast_util_sys" }
cc_ir_sys = { path = "../../../../cargo/rs_bindings_from_cc/cc_ir_sys" }
recording_diagnostic_consumer_sys = { path = "../../../../cargo/rs_bindings_from_cc/recording_diagnostic_consumer_sys" }


[build-dependencies]
crubit_build = { path =  "../../../../cargo/build"}
