# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the Rust crate ir.

[package]
name = "ir"
edition = "2021"

[lib]
path = "../../../rs_bindings_from_cc/ir.rs"

[dependencies]
arc_anyhow = { path = "../../../cargo/common/arc_anyhow" }
code_gen_utils = { path = "../../../cargo/common/code_gen_utils" }
crubit_feature = { path = "../../../cargo/common/crubit_feature" }
error_report = { path = "../../../cargo/common/error_report" }
flagset.workspace = true
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
serde.workspace = true
serde_json.workspace = true
