# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the Rust crate ir_matchers.

[package]
name = "ir_matchers"
edition = "2021"

[lib]
path = "../../../rs_bindings_from_cc/ir_matchers.rs"

[dependencies]
ir = { path = "../../../cargo/rs_bindings_from_cc/ir" }
ir_testing = { path = "../../../cargo/rs_bindings_from_cc/ir_testing" }
token_stream_matchers = { path = "../../../cargo/common/token_stream_matchers" }
token_stream_printer = { path = "../../../cargo/common/token_stream_printer" }
anyhow.workspace = true
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
