# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the cc_libary decl_importer_sys.

[package]
name = "decl_importer_sys"
edition = "2021"

build = "build.rs"

[lib]
path = "lib.rs"

[dependencies]
cc_ir_sys = { path = "../../../cargo/rs_bindings_from_cc/cc_ir_sys" }
lifetime_annotations_sys = { path = "../../../cargo/lifetime_annotations/lifetime_annotations_sys" }
type_lifetimes_sys = { path = "../../../cargo/lifetime_annotations/type_lifetimes_sys" }


[build-dependencies]
crubit_build = { path =  "../../../cargo/build"}
