# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the Rust crate ffi_types.

[package]
name = "ffi_types"
edition.workspace = true

[lib]
path = "../../../common/ffi_types.rs"

[dependencies]
