# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the cc_library type_lifetimes_sys.

[package]
name = "type_lifetimes_sys"
edition = "2021"

build = "build.rs"

[lib]
path = "lib.rs"

[dependencies]
lifetime_sys = { path = "../../../cargo/lifetime_annotations/lifetime_sys" }
lifetime_substitutions_sys = { path = "../../../cargo/lifetime_annotations/lifetime_substitutions_sys" }
lifetime_symbol_table_sys = { path = "../../../cargo/lifetime_annotations/lifetime_symbol_table_sys" }
pointee_type_sys = { path = "../../../cargo/lifetime_annotations/pointee_type_sys" }


[build-dependencies]
crubit_build = { path =  "../../../cargo/build"}
