# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

[package]
name = "collect_instantiations"
edition = "2021"

[lib]
path = "../../collect_instantiations.rs"

[dependencies]
proc-macro2.workspace = true
serde_json.workspace = true
syn.workspace = true
arc_anyhow = { path = "../../../common/car<internal link>_anyhow" }
ffi_types = { path = "../../../common/car<internal link>_types" }
