# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

[package]
name = "generate_bindings"
edition = "2021"

[lib]
path = "../../generate_bindings/lib.rs"

[dependencies]
anyhow.workspace = true
itertools.workspace = true
flagset.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
arc_anyhow = { path = "../../../common/cargo/arc_anyhow" }
code_gen_utils = { path = "../../../common/cargo/code_gen_utils" }
crubit_feature = { path = "../../../common/cargo/crubit_feature" }
error_report = { path = "../../../common/cargo/error_report" }
ffi_types = { path = "../../../common/cargo/ffi_types" }
ir = { path = "../ir" }
memoized = { path = "../../../common/cargo/memoized" }
token_stream_printer = { path = "../../../common/cargo/token_stream_printer" }
